# 是否使用分页器，MacOS和Debian系上默认false，请自行开启
paging = true
# 分页器命令，例如：less -RF / bat / (不推荐) more -e
# 注意：less命令如果不加上-R，在某些系统/发行版上会产生颜色乱码问题
pager_command = "less -RF"  # Linux默认

# 结果中只显示英文（英译、英文例句等）
english_only = false

# 颜色主题，支持：temp/wudao
theme = "temp"

# 格式：http://<IP或域名>:<端口>。设置为空时，系统代理依然会生效
# 如果需要频繁查询长句，可设置此项，否则本地IP有一定概率会被有道服务器暂时屏蔽
http_proxy = ""

# 输出内容前自动清空终端，适合强迫症
clear_screen = false

# （开发中）安装了emoji字体的可以输出一些emoji字符，just for fun
enable_emoji = true

# 是否开启频率提醒：本月第X次查询xxx
freq_alert = true

# 日志配置
[logging]
  # 开启日志记录（程序异常时会记录关键信息，不建议关闭）
  enable = true
  # 默认值：Linux/MacOS为/tmp/kd_<username>.log，windows为%TMPDIR%/kd_<username>.log
  path = ""
  # 日志级别，支持：DEBUG/INFO/WARN/PANIC/FATAL
  level = "WARN"
